"""Stable Dash component identifiers."""

from __future__ import annotations


APP_LOCATION_ID = "app-location"
MANTINE_PROVIDER_ID = "mantine-provider"
OVERVIEW_DOWNLOAD_ID = "overview-download"
APP_SHELL_ID = "app-shell"
APP_NAVBAR_ID = "app-navbar"
APP_NAVBAR_BURGER_ID = "app-navbar-burger"
APP_THEME_TOGGLE_ID = "app-theme-toggle"
APP_METHODS_DRAWER_ID = "app-methods-drawer"
APP_METHODS_DRAWER_OPEN_ID = "app-methods-drawer-open"
APP_METHODS_DRAWER_CLOSE_ID = "app-methods-drawer-close"
APP_LOCALE_STORE_ID = "app-locale-store"
APP_LOCALE_VI_ID = "app-locale-vi"
APP_LOCALE_EN_ID = "app-locale-en"
APP_LOCALE_STATUS_ID = "app-locale-status"
APP_HEADER_CONTENT_ID = "app-header-content"
APP_NAVIGATION_CONTENT_ID = "app-navigation-content"
APP_RELEASE_STRIP_ID = "app-release-strip"
APP_METHODS_DRAWER_CONTENT_ID = "app-methods-drawer-content"
APP_DOCUMENT_METADATA_ID = "app-document-metadata"
APP_DOCUMENT_STATUS_ID = "app-document-status"

OVERVIEW_PAGE_ID = "overview-page"
OVERVIEW_CONTENT_ID = "overview-localized-content"
OVERVIEW_HEATMAP_ID = "overview-e2e-heatmap"
OVERVIEW_PROFILE_ID = "overview-evidence-profile"
OVERVIEW_FINDINGS_ID = "overview-certified-findings"
OVERVIEW_EXPORT_ID = "overview-export"


def kpi_info_id(metric_id: str) -> dict[str, str]:
    """Return a pattern-matching ID for KPI information controls."""

    return {"type": "overview-kpi-info", "metric": metric_id}

EFFECTIVENESS_PAGE_ID = "effectiveness-page"
EFFECTIVENESS_CONTENT_ID = "effectiveness-localized-content"
EFFECTIVENESS_UI_STATE_ID = "effectiveness-ui-state"
EFFECTIVENESS_TABS_ID = "effectiveness-tabs"
EFFECTIVENESS_FOCUS_STORE_ID = "effectiveness-focus-store"
EFFECTIVENESS_FOCUS_CHIP_ID = "effectiveness-focus-chip"
EFFECTIVENESS_CLEAR_FOCUS_ID = "effectiveness-clear-focus"
EFFECTIVENESS_RELIABILITY_MAP_ID = "effectiveness-reliability-map"
EFFECTIVENESS_FOCUS_PANEL_ID = "effectiveness-focus-panel"
EFFECTIVENESS_LOSS_ID = "effectiveness-loss-decomposition"
EFFECTIVENESS_OPTION_GRID_ID = "effectiveness-option-grid"
EFFECTIVENESS_CONDITIONAL_METRIC_ID = "effectiveness-conditional-metric"
EFFECTIVENESS_CONDITIONAL_HEATMAP_ID = "effectiveness-conditional-heatmap"
EFFECTIVENESS_CONDITIONAL_PANEL_ID = "effectiveness-conditional-panel"
EFFECTIVENESS_GAP_ID = "effectiveness-operational-conditional-gap"
EFFECTIVENESS_FAILURE_GRID_ID = "effectiveness-failure-grid"
EFFECTIVENESS_EFFECT_SIZE_ID = "effectiveness-effect-size"
EFFECTIVENESS_SENSITIVITY_ID = "effectiveness-sensitivity-summary"
EFFECTIVENESS_CONTRAST_FAMILY_ID = "effectiveness-contrast-family"
EFFECTIVENESS_CONTRAST_GRID_ID = "effectiveness-contrast-grid"

EFFECTIVENESS_EXPORT_ID = "effectiveness-export"
EFFECTIVENESS_DOWNLOAD_ID = "effectiveness-download"
EFFECTIVENESS_CONDITIONAL_CONTRAST_GRID_ID = (
    "effectiveness-conditional-contrast-grid"
)


MECHANISMS_PAGE_ID = "mechanisms-page"
MECHANISMS_CONTENT_ID = "mechanisms-localized-content"
MECHANISMS_UI_STATE_ID = "mechanisms-ui-state"
MECHANISMS_TABS_ID = "mechanisms-tabs"
MECHANISMS_DOWNLOAD_ID = "mechanisms-download"
MECHANISMS_EXPORT_ID = "mechanisms-export"
MECHANISMS_EVIDENCE_COMPOSITION_ID = "mechanisms-evidence-composition"
MECHANISMS_COVERAGE_DIVERSITY_ID = "mechanisms-coverage-diversity"
MECHANISMS_EVIDENCE_GRID_ID = "mechanisms-evidence-grid"
MECHANISMS_UTILIZATION_METRIC_ID = "mechanisms-utilization-metric"
MECHANISMS_UTILIZATION_MATRIX_ID = "mechanisms-utilization-matrix"
MECHANISMS_UTILIZATION_PROFILE_ID = "mechanisms-utilization-profile"
MECHANISMS_UTILIZATION_SCATTER_ID = "mechanisms-utilization-scatter"
MECHANISMS_UTILIZATION_GRID_ID = "mechanisms-utilization-grid"
MECHANISMS_CLAIM_STATUS_ID = "mechanisms-claim-status"
MECHANISMS_CLAIM_DIFFICULTY_ID = "mechanisms-claim-difficulty"
MECHANISMS_REASON_GRID_ID = "mechanisms-reason-grid"
MECHANISMS_NARRATIVE_STRUCTURE_ID = "mechanisms-narrative-structure"
MECHANISMS_POLICY_COMPLIANCE_ID = "mechanisms-policy-compliance"
MECHANISMS_PIPELINE_COMPLETION_ID = "mechanisms-pipeline-completion"
MECHANISMS_FAILURE_MATRIX_ID = "mechanisms-failure-matrix"
MECHANISMS_FAILURE_GRID_ID = "mechanisms-failure-grid"

MECHANISMS_FOCUS_STORE_ID = "mechanisms-focus-store"
MECHANISMS_UTILIZATION_PANEL_ID = "mechanisms-utilization-panel"
MECHANISMS_CLAIM_MEASURE_ID = "mechanisms-claim-measure"

DECISION_PAGE_ID = "decision-page"
DECISION_TABS_ID = "decision-tabs"
DECISION_SCENARIO_ID = "decision-scenario"
DECISION_SCENARIO_DESCRIPTION_ID = "decision-scenario-description"
DECISION_X_AXIS_ID = "decision-x-axis"
DECISION_TRADEOFF_ID = "decision-tradeoff-map"
DECISION_RECOMMENDATION_ID = "decision-recommendation-panel"
DECISION_CONTRIBUTION_ID = "decision-contribution-profile"
DECISION_CONTRIBUTION_SUMMARY_ID = "decision-contribution-summary"
DECISION_TOP_RANKING_ID = "decision-top-ranking"
DECISION_FULL_RANKING_GRID_ID = "decision-full-ranking-grid"
DECISION_EXPORT_ID = "decision-export"
DECISION_DOWNLOAD_ID = "decision-download"
DECISION_WHAT_IF_PANEL_ID = "decision-what-if-panel"
DECISION_WHAT_IF_COMPARISON_ID = "decision-what-if-contribution-comparison"
DECISION_WHAT_IF_RANK_SUMMARY_ID = "decision-what-if-rank-summary"
DECISION_WHAT_IF_GRID_ID = "decision-what-if-grid"
DECISION_RESET_WEIGHTS_ID = "decision-reset-weights"
DECISION_EQUAL_WEIGHTS_ID = "decision-equal-weights"
DECISION_CLIPBOARD_ID = "decision-clipboard"
DECISION_COMPARISON_OPEN_ID = "decision-comparison-open"
DECISION_COMPARISON_CLOSE_ID = "decision-comparison-close"
DECISION_COMPARISON_DRAWER_ID = "decision-comparison-drawer"
DECISION_COMPARISON_OPTIONS_ID = "decision-comparison-options"
DECISION_COMPARISON_TABLE_ID = "decision-comparison-table"

ROBUSTNESS_PAGE_ID = "robustness-page"
ROBUSTNESS_TABS_ID = "robustness-tabs"
ROBUSTNESS_EXPORT_ID = "robustness-export"
ROBUSTNESS_DOWNLOAD_ID = "robustness-download"
ROBUSTNESS_MEASUREMENT_METRIC_ID = "robustness-measurement-metric"
ROBUSTNESS_MEASUREMENT_MODEL_ID = "robustness-measurement-model"
ROBUSTNESS_MEASUREMENT_SHIFT_ID = "robustness-measurement-shift"
ROBUSTNESS_MEASUREMENT_PANEL_ID = "robustness-measurement-panel"
ROBUSTNESS_MEASUREMENT_FOCUS_STORE_ID = "robustness-measurement-focus-store"
ROBUSTNESS_MEASUREMENT_DELTA_ID = "robustness-measurement-delta"
ROBUSTNESS_MEASUREMENT_TEST_SUMMARY_ID = "robustness-measurement-test-summary"
ROBUSTNESS_MEASUREMENT_TEST_GRID_ID = "robustness-measurement-test-grid"
ROBUSTNESS_TEMPLATE_METRIC_ID = "robustness-template-metric"
ROBUSTNESS_TEMPLATE_MODEL_ID = "robustness-template-model"
ROBUSTNESS_TEMPLATE_SCOPE_ID = "robustness-template-scope"
ROBUSTNESS_TEMPLATE_PROGRESSION_ID = "robustness-template-progression"
ROBUSTNESS_TEMPLATE_UPLIFT_ID = "robustness-template-uplift"
ROBUSTNESS_TEMPLATE_DELTA_ID = "robustness-template-delta"
ROBUSTNESS_TEMPLATE_TEST_SUMMARY_ID = "robustness-template-test-summary"
ROBUSTNESS_TEMPLATE_COVERAGE_ID = "robustness-template-coverage"
ROBUSTNESS_TEMPLATE_TEST_GRID_ID = "robustness-template-test-grid"
ROBUSTNESS_TEMPLATE_GENERATION_GRID_ID = "robustness-template-generation-grid"

# Page 6 — Case Explorer.
CASES_PAGE_ID = "cases-page"
CASES_EXPORT_ID = "cases-export"
CASES_DOWNLOAD_ID = "cases-download"
CASES_STRATUM_FILTER_ID = "cases-stratum-filter"
CASES_OUTCOME_FILTER_ID = "cases-outcome-filter"
CASES_COMPLETENESS_FILTER_ID = "cases-completeness-filter"
CASES_RESET_FILTERS_ID = "cases-reset-filters"
CASES_COHORT_ID = "cases-cohort-landscape"
CASES_SELECTED_CASE_ID = "cases-selected-case"
CASES_SELECTED_OUTSIDE_NOTE_ID = "cases-selected-outside-note"
CASES_BROWSER_GRID_ID = "cases-browser-grid"
CASES_SNAPSHOT_ID = "cases-snapshot"
CASES_MATRIX_METRIC_ID = "cases-matrix-metric"
CASES_MATRIX_ID = "cases-performance-matrix"
CASES_FOCUSED_GENERATION_ID = "cases-focused-generation"
CASES_EVIDENCE_ID = "cases-evidence-condition"
CASES_MODEL_ID = "cases-focused-model"
CASES_EVIDENCE_PACKAGE_ID = "cases-evidence-package"
CASES_UTILIZATION_ID = "cases-evidence-utilization"
CASES_CLAIM_COMPOSITION_ID = "cases-claim-composition"
CASES_NARRATIVE_STRUCTURE_ID = "cases-narrative-structure"
CASES_VALIDATOR_ID = "cases-validator-sensitivity"
CASES_TEMPLATE_COMPARISON_ID = "cases-template-comparison"
CASES_FULL_GRID_ID = "cases-full-generation-grid"

# Page 7 — Reproducibility & Methods.
METHODS_PAGE_ID = "methods-page"
METHODS_TABS_ID = "methods-tabs"
METHODS_EXPORT_ID = "methods-export"
METHODS_DOWNLOAD_ID = "methods-download"
METHODS_RQ_FILTER_ID = "methods-rq-filter"
METHODS_RQ_CONTAINER_ID = "methods-rq-container"
METHODS_HEADLINE_SECTION_ID = "methods-headline-section"
METHODS_HEADLINE_CONTAINER_ID = "methods-headline-container"
METHODS_HEADLINE_GRID_ID = "methods-headline-grid"
METHODS_DICTIONARY_SEARCH_ID = "methods-dictionary-search"
METHODS_DICTIONARY_DATASET_ID = "methods-dictionary-dataset"
METHODS_DICTIONARY_TIER_ID = "methods-dictionary-tier"
METHODS_DICTIONARY_ROLE_ID = "methods-dictionary-role"
METHODS_DICTIONARY_INTERNAL_ID = "methods-dictionary-include-internal"
METHODS_DICTIONARY_CONTAINER_ID = "methods-dictionary-container"
METHODS_DICTIONARY_GRID_ID = "methods-dictionary-grid"
METHODS_ARTIFACT_GRID_ID = "methods-artifact-grid"
METHODS_VISIBILITY_PROFILE_ID = "methods-visibility-profile"
METHODS_LIMITATION_CATEGORY_ID = "methods-limitation-category"
METHODS_LIMITATION_CONTAINER_ID = "methods-limitation-container"
