export const qk = {
  health: ["system", "health"] as const,
  readiness: ["system", "readiness"] as const,
  version: ["system", "version"] as const,
  capabilities: ["system", "capabilities"] as const,
  stages: ["registry", "stages"] as const,
  flows: ["registry", "flows"] as const,
  deployments: ["registry", "deployments"] as const,

  runsRoot: ["runs"] as const,
  runDetailsRoot: ["run"] as const,
  runs: (q: unknown) => ["runs", q] as const,
  run: (id: string) => ["run", id] as const,
  runStages: (id: string) => ["run", id, "stages"] as const,
  runEvents: (id: string) => ["run", id, "events"] as const,
  runOutputs: (id: string) => ["run", id, "outputs"] as const,
  runReceipt: (id: string) => ["run", id, "receipt"] as const,

  artifactsRoot: ["artifacts"] as const,
  artifactDetailsRoot: ["artifact"] as const,
  artifacts: (q: unknown) => ["artifacts", q] as const,
  artifact: (id: string) => ["artifact", id] as const,
  artifactFiles: (id: string) => ["artifact", id, "files"] as const,
  artifactLineage: (id: string, q: unknown) => ["artifact", id, "lineage", q] as const,
  artifactGates: (id: string) => ["artifact", id, "gates"] as const,
  artifactReleases: (id: string) => ["artifact", id, "releases"] as const,

  gatesRoot: ["gates"] as const,
  gateDetailsRoot: ["gate"] as const,
  gates: (q: unknown) => ["gates", q] as const,
  gate: (id: string) => ["gate", id] as const,
  gateHistory: (id: string) => ["gate", id, "history"] as const,
  evaluation: (id: string) => ["evaluation", id] as const,

  approvalsRoot: ["approvals"] as const,
  approvalDetailsRoot: ["approval"] as const,
  approvals: (q: unknown) => ["approvals", q] as const,
  approval: (id: string) => ["approval", id] as const,

  releasesRoot: ["releases"] as const,
  releaseDetailsRoot: ["release"] as const,
  releases: (q: unknown) => ["releases", q] as const,
  release: (id: string) => ["release", id] as const,
  releaseArtifacts: (id: string) => ["release", id, "artifacts"] as const,
  releaseGates: (id: string) => ["release", id, "gates"] as const,
  releaseDecisions: (id: string) => ["release", id, "decisions"] as const,

  modelsRoot: ["models"] as const,
  modelVersions: (name: string) => ["models", name, "versions"] as const,
  modelVersion: (name: string, version: string) => ["models", name, version] as const,

  operationsRoot: ["operations"] as const,
  operationDetailsRoot: ["operation"] as const,
  operations: (q: unknown) => ["operations", q] as const,
  operation: (id: string) => ["operation", id] as const,
};
