from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..description import StoredArtifactDescription
from ..models import ArtifactManifestV3, ArtifactPackage, ArtifactReference, ArtifactVerificationResult


class ArtifactStore(Protocol):
    def put_package(self, package: ArtifactPackage) -> ArtifactReference: ...
    def get_manifest(self, artifact_id: str) -> ArtifactManifestV3: ...
    def describe(self, artifact_id: str) -> StoredArtifactDescription: ...
    def download(self, artifact_id: str, destination: Path) -> Path: ...
    def verify(self, artifact_id: str) -> ArtifactVerificationResult: ...
    def exists(self, artifact_id: str) -> bool: ...
    def list_artifact_ids(self) -> set[str]: ...
