export const CLAIM_VALIDATION_SCHEMA_VERSION = "claim_validation_v4";
export const CLAIM_VALIDATOR_VERSION = "claim_validator_v4.0.0";
export const CLAIM_VALIDATION_MANIFEST_VERSION = "claim_validation_manifest_v3";
export const CLAIM_VALIDATION_SUMMARY_VERSION = "claim_validation_summary_v3";
export const DETERMINISTIC_RESULT_TIMESTAMP = "2026-07-23T00:00:00.000Z";

export const EXECUTION_STATUS = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;

export const VALIDATION_STATUS = {
  SUPPORTED: "SUPPORTED",
  UNSUPPORTED: "UNSUPPORTED",
  CONTRADICTED: "CONTRADICTED",
  NOT_VERIFIABLE: "NOT_VERIFIABLE",
  NOT_APPLICABLE: "NOT_APPLICABLE",
} as const;

export const VALIDATOR_MODE = {
  DETERMINISTIC: "DETERMINISTIC",
  SEMANTIC: "SEMANTIC",
  HUMAN_ADJUDICATED: "HUMAN_ADJUDICATED",
} as const;

export const REASON_CODE = {
  EXACT_MATCH: "EXACT_MATCH",
  NORMALIZED_MATCH: "NORMALIZED_MATCH",
  TOLERANCE_MATCH: "TOLERANCE_MATCH",
  NOT_APPLICABLE_BY_POLICY: "NOT_APPLICABLE_BY_POLICY",
  PREDICTION_LABEL_MISMATCH: "PREDICTION_LABEL_MISMATCH",
  PREDICTION_PROBABILITY_MISMATCH: "PREDICTION_PROBABILITY_MISMATCH",
  PREDICTION_THRESHOLD_MISMATCH: "PREDICTION_THRESHOLD_MISMATCH",
  PREDICTION_NOT_EXPOSED: "PREDICTION_NOT_EXPOSED",
  PREDICTION_VALUE_UNAVAILABLE: "PREDICTION_VALUE_UNAVAILABLE",
  FEATURE_NOT_EXPOSED: "FEATURE_NOT_EXPOSED",
  CONCEPT_NOT_EXPOSED: "CONCEPT_NOT_EXPOSED",
  DIRECTION_NOT_EXPOSED: "DIRECTION_NOT_EXPOSED",
  MAGNITUDE_NOT_EXPOSED: "MAGNITUDE_NOT_EXPOSED",
  RANKING_NOT_EXPOSED: "RANKING_NOT_EXPOSED",
  NUMERIC_SOURCE_NOT_EXPOSED: "NUMERIC_SOURCE_NOT_EXPOSED",
  FEATURE_NOT_FOUND_IN_EVIDENCE: "FEATURE_NOT_FOUND_IN_EVIDENCE",
  FEATURE_ALIAS_UNRESOLVED: "FEATURE_ALIAS_UNRESOLVED",
  FEATURE_ID_MISMATCH: "FEATURE_ID_MISMATCH",
  CONCEPT_NOT_FOUND_IN_EVIDENCE: "CONCEPT_NOT_FOUND_IN_EVIDENCE",
  CONCEPT_MEMBERSHIP_MISMATCH: "CONCEPT_MEMBERSHIP_MISMATCH",
  CONCEPT_ID_MISMATCH: "CONCEPT_ID_MISMATCH",
  DIRECTION_REVERSED: "DIRECTION_REVERSED",
  DIRECTION_NEUTRAL: "DIRECTION_NEUTRAL",
  DIRECTION_MIXED_OR_UNKNOWN: "DIRECTION_MIXED_OR_UNKNOWN",
  DIRECTION_SOURCE_MISSING: "DIRECTION_SOURCE_MISSING",
  NUMERIC_EXACT_MISMATCH: "NUMERIC_EXACT_MISMATCH",
  NUMERIC_OUTSIDE_TOLERANCE: "NUMERIC_OUTSIDE_TOLERANCE",
  NUMERIC_UNIT_MISMATCH: "NUMERIC_UNIT_MISMATCH",
  NUMERIC_ROLE_UNSUPPORTED: "NUMERIC_ROLE_UNSUPPORTED",
  NUMERIC_SOURCE_MISSING: "NUMERIC_SOURCE_MISSING",
  NUMERIC_NORMALIZATION_FAILED: "NUMERIC_NORMALIZATION_FAILED",
  RANKING_UNSUPPORTED: "RANKING_UNSUPPORTED",
  RANK_TIE_AMBIGUOUS: "RANK_TIE_AMBIGUOUS",
  RANK_SOURCE_MISSING: "RANK_SOURCE_MISSING",
  MAGNITUDE_UNSUPPORTED: "MAGNITUDE_UNSUPPORTED",
  MAGNITUDE_MATCH: "MAGNITUDE_MATCH",
  MAGNITUDE_OVERSTATED: "MAGNITUDE_OVERSTATED",
  MAGNITUDE_UNDERSTATED: "MAGNITUDE_UNDERSTATED",
  MAGNITUDE_SOURCE_MISSING: "MAGNITUDE_SOURCE_MISSING",
  MAGNITUDE_SEMANTICS_UNSUPPORTED: "MAGNITUDE_SEMANTICS_UNSUPPORTED",
  SEMANTIC_SOURCE_UNFROZEN: "SEMANTIC_SOURCE_UNFROZEN",
  SEMANTIC_SUBTYPE_UNRESOLVED: "SEMANTIC_SUBTYPE_UNRESOLVED",
  CERTAINTY_OVERCLAIM: "CERTAINTY_OVERCLAIM",
  UNCERTAINTY_NOT_GROUNDED: "UNCERTAINTY_NOT_GROUNDED",
  CAUSAL_OVERCLAIM: "CAUSAL_OVERCLAIM",
  GUARANTEE_OVERCLAIM: "GUARANTEE_OVERCLAIM",
  UNSUPPORTED_RECOMMENDATION: "UNSUPPORTED_RECOMMENDATION",
  POLICY_RULE_NOT_APPLICABLE: "POLICY_RULE_NOT_APPLICABLE",
  INVALID_CLAIM_SHAPE: "INVALID_CLAIM_SHAPE",
  CLAIM_JOIN_FAILED: "CLAIM_JOIN_FAILED",
  GENERATION_JOIN_FAILED: "GENERATION_JOIN_FAILED",
  EVIDENCE_JOIN_FAILED: "EVIDENCE_JOIN_FAILED",
  POLICY_LOAD_FAILED: "POLICY_LOAD_FAILED",
  NORMALIZATION_FAILED: "NORMALIZATION_FAILED",
  UNSUPPORTED_CLAIM_TYPE: "UNSUPPORTED_CLAIM_TYPE",
  OUTPUT_SCHEMA_FAILED: "OUTPUT_SCHEMA_FAILED",
} as const;

export type ReasonCode = (typeof REASON_CODE)[keyof typeof REASON_CODE];
