from __future__ import annotations

from typing import Protocol

from ..db.models import (
    Approval,
    ArtifactFileRecord,
    ArtifactRecord,
    AuditEvent,
    EnvironmentSnapshot,
    GateEvaluation,
    GateResult,
    GateWaiver,
    LineageEdge,
    OrchestrationBinding,
    PipelineRun,
    PipelineRunReceipt,
    PromotionDecision,
    ReleaseArtifact,
    ReleaseRecord,
    RunEvent,
    StageRun,
    StageRunOutput,
)


class OpsRepository(Protocol):
    # Immutable artifact metadata and lineage.
    def get_artifact(self, artifact_id: str) -> ArtifactRecord | None: ...
    def get_artifact_by_manifest_hash(self, sha256: str) -> ArtifactRecord | None: ...
    def list_artifact_ids(self) -> set[str]: ...
    def add_artifact(self, record: ArtifactRecord) -> None: ...
    def add_artifact_file(self, record: ArtifactFileRecord) -> None: ...
    def add_lineage_edge(self, edge: LineageEdge) -> None: ...
    def descendants(self, artifact_id: str) -> set[str]: ...
    def ancestors(self, artifact_id: str) -> set[str]: ...

    # Release and gate state.
    def get_release(self, release_id: str) -> ReleaseRecord | None: ...
    def add_release(self, record: ReleaseRecord) -> None: ...
    def add_release_artifact(self, record: ReleaseArtifact) -> None: ...
    def release_artifact_ids(self, release_id: str) -> set[str]: ...
    def blocking_gates(self, scope_type: str, scope_id: str) -> list[GateResult]: ...
    def get_gate_result(
        self, gate_id: str, scope_type: str, scope_id: str
    ) -> GateResult | None: ...
    def add_gate_result(self, record: GateResult) -> None: ...
    def get_gate_evaluation(self, evaluation_id: str) -> GateEvaluation | None: ...
    def get_gate_evaluation_by_key(self, key: str) -> GateEvaluation | None: ...
    def list_gate_evaluations(
        self, gate_id: str, scope_type: str, scope_id: str
    ) -> list[GateEvaluation]: ...
    def add_gate_evaluation(self, record: GateEvaluation) -> None: ...
    def get_gate_result_by_id(self, gate_result_id: str) -> GateResult | None: ...
    def get_gate_waiver(self, waiver_id: str) -> GateWaiver | None: ...
    def get_gate_waiver_by_request_key(self, key: str) -> GateWaiver | None: ...
    def active_gate_waiver(
        self, gate_result_id: str, evaluation_id: str
    ) -> GateWaiver | None: ...
    def list_gate_waivers(
        self, *, scope_type: str | None = None, scope_id: str | None = None
    ) -> list[GateWaiver]: ...
    def add_gate_waiver(self, record: GateWaiver) -> None: ...
    def get_promotion_decision(self, decision_id: str) -> PromotionDecision | None: ...
    def get_promotion_decision_by_key(self, key: str) -> PromotionDecision | None: ...
    def list_promotion_decisions(
        self, *, target_type: str | None = None, target_id: str | None = None
    ) -> list[PromotionDecision]: ...
    def add_promotion_decision(self, record: PromotionDecision) -> None: ...
    def approvals(self, target_type: str, target_id: str) -> list[Approval]: ...
    def get_approval(self, approval_id: str) -> Approval | None: ...
    def get_approval_by_request_key(self, request_key: str) -> Approval | None: ...
    def list_approvals(
        self, *, status: str | None = None, pipeline_run_id: str | None = None
    ) -> list[Approval]: ...
    def add_approval(self, record: Approval) -> None: ...

    # Environment and execution state.
    def get_environment_snapshot(self, snapshot_id: str) -> EnvironmentSnapshot | None: ...
    def add_environment_snapshot(self, record: EnvironmentSnapshot) -> None: ...
    def get_pipeline_run(self, run_id: str) -> PipelineRun | None: ...
    def get_pipeline_run_by_idempotency_key(self, key: str) -> PipelineRun | None: ...
    def list_pipeline_runs(self) -> list[PipelineRun]: ...
    def add_pipeline_run(self, record: PipelineRun) -> None: ...
    def get_pipeline_run_receipt(
        self, pipeline_run_id: str
    ) -> PipelineRunReceipt | None: ...
    def add_pipeline_run_receipt(self, record: PipelineRunReceipt) -> None: ...
    def get_stage_run(self, stage_run_id: str) -> StageRun | None: ...
    def list_stage_runs(self, pipeline_run_id: str) -> list[StageRun]: ...
    def add_stage_run(self, record: StageRun) -> None: ...
    def add_run_event(self, record: RunEvent) -> None: ...
    def list_run_events(self, pipeline_run_id: str) -> list[RunEvent]: ...

    # Prefect bindings and named output identity.
    def get_orchestration_binding_by_key(
        self, orchestrator: str, key: str, attempt_number: int
    ) -> OrchestrationBinding | None: ...
    def get_orchestration_binding_for_prefect(
        self,
        orchestrator: str,
        prefect_flow_run_id: str,
        prefect_task_run_id: str | None,
    ) -> OrchestrationBinding | None: ...
    def list_orchestration_bindings(self) -> list[OrchestrationBinding]: ...
    def orchestration_bindings_by_key(
        self, orchestrator: str, key: str
    ) -> list[OrchestrationBinding]: ...
    def add_orchestration_binding(self, record: OrchestrationBinding) -> None: ...
    def get_stage_output(
        self, stage_run_id: str, output_name: str
    ) -> StageRunOutput | None: ...
    def stage_outputs(self, stage_run_id: str) -> list[StageRunOutput]: ...
    def add_stage_output(self, record: StageRunOutput) -> None: ...

    def artifacts_for_stage_run(self, stage_run_id: str) -> set[str]: ...
    def succeeded_stage_runs_without_artifacts(self) -> set[str]: ...
    def add_audit_event(self, record: AuditEvent) -> None: ...
    def flush(self) -> None: ...
